### ISSUE TITLE
Checkpoints on the Hugging Face Hub?

### ISSUE THREAD

**Issue by sanchit-gandhi** [futo-org/whisper-acft#2]
Hey @abb128 - congrats on this great project. It was super interesting reading how you tackled the problem of a fixed context length for Whisper!

I'm very excited to try the model in the Transformers library. However, I noticed that neither the Whisper cpp nor Transformers weights are not published on the Hugging Face Hub. Would you be open to pushing your weights to the Hugging Face Hub, in order to:
1. Increase the visibility of your work through a Hub presence
2. Reduce the barrier of entry to using your checkpoints, by enabling anyone in the community to load your model with two lines of code:
```python
from transformers import WhisperForConditionalGeneration

model = WhisperForConditionalGeneration.from_pretrained("your-username/your-model-name")
```

It's super easy to push the Transformers weights to the Hub with one line of code:
```python
from transformers import WhisperForConditionalGeneration

model = WhisperForConditionalGeneration.from_pretrained("./local/path/to/checkpoint")
model.push_to_hub("your-model-name")
```

For the Whisper cpp weights, you can follow [this guide](https://huggingface.co/docs/huggingface_hub/en/guides/upload). You can also then draft a pretty model card that explains how to use the model, e.g. in the style of [distil-large-v3](https://huggingface.co/distil-whisper/distil-large-v3).

**Comment by abb128** [comment]
We've uploaded checkpoints to our HF: https://huggingface.co/futo-org
